name: remap
version: 2.0.0
description: Converts objects to json and formurlencoded maps

authors:
- Alexander Polyankin <alexander.polyankin@team.wrike.com>

homepage: https://github.com/wrike/remap

environment:
  sdk: '>=2.0.0-dev <3.0.0'
