name: remap
version: 1.0.0
description: Map-based readers and writers for json and formurlencoded serialization and deserialization.

authors:
- Alexander Polyankin <alexander.polyankin@team.wrike.com>
- Max Grebenschikov <maxim.grebenshikov@team.wrike.com>

homepage: https://github.com/ranquild/remap

environment:
  sdk: '>=2.0.0-dev <3.0.0'
